constants:
  Pamb: 101.325
  Tamb: 289
  mach_inlet: 0.5
  R: 0.2871
  f: 0.025
  mc2_bounds: [50,100]

diffuser:
  pr_dd: 1
  d: 0
  gamma_diff: 1.401

compressor:
  c1: 0.1764
  c2: 0.00907
  c3: 0.8
  c4: 0.00001
  c5: 9.724
  nc2d: 10000
  eff_c_dp: 0.88
  u: 0.1
  gamma_comp: 1.384

combustor:
  b1: 9.068
  b2: 0
  delta_h: 41800
  eff_burner_dp: 0.91
  gamma_b: 1.341

turbine:
  k1: 1
  k2: 0.2
  nc4d: 4000
  mc4c: 15.87
  eff_t_d: 0.9
  pr_tc: 0.28

shaft:
  s1: 0
  s2: 0

nozzle:
  a1: 0
  m_n: 88.08
  eff_n_d: 0.98

thermodynamics:
  gamma_m1: 1.384
  gamma_m2: 1.328
  gamma5: 1.328
  cp1: ((gamma_m1 * R) / (gamma_m1 - 1))
  cp2: ((gamma_m2 * R) / (gamma_m2 - 1))

output:
  res_fldr: "./"